// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	AddAuthToken(ctx context.Context, in *AddAuthTokenRequest, opts ...grpc.CallOption) (*AddAuthTokenResponse, error)
	StartLogin(ctx context.Context, in *StartAuthRequest, opts ...grpc.CallOption) (*StartAuthResponse, error)
	CompleteLogin(ctx context.Context, in *CompleteAuthRequest, opts ...grpc.CallOption) (*CompleteAuthResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) AddAuthToken(ctx context.Context, in *AddAuthTokenRequest, opts ...grpc.CallOption) (*AddAuthTokenResponse, error) {
	out := new(AddAuthTokenResponse)
	err := c.cc.Invoke(ctx, "/protos.AuthService/AddAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartLogin(ctx context.Context, in *StartAuthRequest, opts ...grpc.CallOption) (*StartAuthResponse, error) {
	out := new(StartAuthResponse)
	err := c.cc.Invoke(ctx, "/protos.AuthService/StartLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CompleteLogin(ctx context.Context, in *CompleteAuthRequest, opts ...grpc.CallOption) (*CompleteAuthResponse, error) {
	out := new(CompleteAuthResponse)
	err := c.cc.Invoke(ctx, "/protos.AuthService/CompleteLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	AddAuthToken(context.Context, *AddAuthTokenRequest) (*AddAuthTokenResponse, error)
	StartLogin(context.Context, *StartAuthRequest) (*StartAuthResponse, error)
	CompleteLogin(context.Context, *CompleteAuthRequest) (*CompleteAuthResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) AddAuthToken(context.Context, *AddAuthTokenRequest) (*AddAuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAuthToken not implemented")
}
func (UnimplementedAuthServiceServer) StartLogin(context.Context, *StartAuthRequest) (*StartAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedAuthServiceServer) CompleteLogin(context.Context, *CompleteAuthRequest) (*CompleteAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteLogin not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_AddAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthService/AddAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddAuthToken(ctx, req.(*AddAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthService/StartLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartLogin(ctx, req.(*StartAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CompleteLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CompleteLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthService/CompleteLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CompleteLogin(ctx, req.(*CompleteAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAuthToken",
			Handler:    _AuthService_AddAuthToken_Handler,
		},
		{
			MethodName: "StartLogin",
			Handler:    _AuthService_StartLogin_Handler,
		},
		{
			MethodName: "CompleteLogin",
			Handler:    _AuthService_CompleteLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/auth.proto",
}
