# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import tickers_pb2 as protos_dot_tickers__pb2


class TickerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTickers = channel.unary_unary(
                '/protos.TickerService/GetTickers',
                request_serializer=protos_dot_tickers__pb2.GetTickersRequest.SerializeToString,
                response_deserializer=protos_dot_tickers__pb2.GetTickersResponse.FromString,
                )


class TickerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTickers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTickers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTickers,
                    request_deserializer=protos_dot_tickers__pb2.GetTickersRequest.FromString,
                    response_serializer=protos_dot_tickers__pb2.GetTickersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.TickerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TickerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTickers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.TickerService/GetTickers',
            protos_dot_tickers__pb2.GetTickersRequest.SerializeToString,
            protos_dot_tickers__pb2.GetTickersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
